"""Tests for the smart content generator."""
from __future__ import annotations

from agent_framework.core.content_generator import generate_content


class TestPythonGeneration:
    def test_fastapi_file_generates_fastapi_app(self):
        content = generate_content("main.py", "fastapi app with CRUD routes")
        assert "FastAPI" in content
        assert "app.get" in content
        assert "app.post" in content

    def test_test_file_generates_pytest_suite(self):
        content = generate_content("tests/test_app.py", "pytest tests")
        assert "import pytest" in content
        assert "class Test" in content
        assert "def test_" in content

    def test_cli_file_generates_argparse(self):
        content = generate_content("cli.py", "command line CLI tool")
        assert "argparse" in content
        assert "def main" in content

    def test_data_file_generates_data_analysis(self):
        content = generate_content("analysis.py", "data analysis with pandas csv")
        assert "import csv" in content
        assert "def summarize" in content

    def test_generic_python_generates_dataclass(self):
        content = generate_content("models.py", "some python module")
        assert "dataclass" in content or "class " in content

    def test_test_prefix_forces_test_template(self):
        content = generate_content("test_models.py", "generic task")
        assert "import pytest" in content


class TestShellAndDocker:
    def test_sh_generates_bash_script(self):
        content = generate_content("setup.sh", "")
        assert "#!/usr/bin/env bash" in content
        assert "set -euo pipefail" in content

    def test_dockerfile_generates_docker_image(self):
        content = generate_content("Dockerfile", "docker image")
        assert "FROM python:" in content
        assert "WORKDIR" in content

    def test_dockerfile_extensionless_path(self):
        content = generate_content("/tmp/project/Dockerfile", "")
        assert "FROM python:" in content


class TestConfigAndMarkup:
    def test_json_generates_config(self):
        content = generate_content("config.json", "")
        assert '"app"' in content
        assert '"version"' in content

    def test_yaml_generates_config(self):
        content = generate_content("config.yaml", "")
        assert "app:" in content
        assert "server:" in content

    def test_html_generates_page(self):
        content = generate_content("index.html", "")
        assert "<!DOCTYPE html>" in content
        assert "<html" in content

    def test_readme_generates_readme(self):
        content = generate_content("README.md", "")
        assert "## Overview" in content
        assert "## Getting Started" in content
        assert "Generated by **apathy**" in content

    def test_makefile_generates_targets(self):
        content = generate_content("Makefile", "")
        assert "install" in content
        assert "test" in content
        assert "clean" in content

    def test_gitignore_generates_patterns(self):
        content = generate_content(".gitignore", "")
        assert "__pycache__/" in content
        assert ".venv/" in content

    def test_env_example_generates_env_template(self):
        content = generate_content(".env.example", "")
        assert "APP_ENV" in content
        assert "DATABASE_URL" in content


class TestRequirements:
    def test_requirements_fastapi_includes_fastapi(self):
        content = generate_content("requirements.txt", "fastapi project")
        assert "fastapi" in content
        assert "uvicorn" in content

    def test_requirements_generic_has_comment(self):
        content = generate_content("requirements.txt", "general project")
        assert "pydantic" in content


class TestYearSubstitution:
    def test_readme_year_is_valid(self):
        content = generate_content("README.md", "")
        # Should not contain literal "{year}" or "{date[:4]}" — must be substituted
        assert "{year}" not in content
        assert "{date[" not in content
        import re
        years = re.findall(r"\b20\d{2}\b", content)
        assert len(years) >= 1, "Expected a 4-digit year in README"

    def test_no_unresolved_template_placeholders(self):
        import re
        # Template var names used in our ctx dict — these should all be substituted.
        template_vars = {"title", "name", "class_name", "date", "year"}
        for path in ["main.py", "config.json", "README.md", "Dockerfile", ".env.example"]:
            content = generate_content(path, "fastapi project")
            # Look for {word} patterns and flag only ones that are our template vars.
            found = re.findall(r"\{([a-z_]+)\}", content)
            leftover = [f for f in found if f in template_vars]
            assert leftover == [], f"{path} has unresolved template vars: {leftover}"
