"""Smart file content generator for the MockProvider.

Produces realistic, runnable template content based on file extension
and task context — no LLM needed. Used when MockProvider receives a
write_file request without explicit inline content.
"""
from __future__ import annotations

import os
import re
from datetime import datetime


def _title(path: str) -> str:
    """Derive a human-readable title from a file path."""
    name = os.path.splitext(os.path.basename(path))[0]
    return name.replace("_", " ").replace("-", " ").title()


def _detect_topic(task_text: str) -> str:
    """Return a broad topic tag from the task description."""
    lower = task_text.lower()
    if any(k in lower for k in ("fastapi", "api", "endpoint", "route", "rest")):
        return "fastapi"
    if any(k in lower for k in ("flask", "webapp", "web app")):
        return "flask"
    if any(k in lower for k in ("cli", "command line", "argparse", "typer", "click")):
        return "cli"
    if any(k in lower for k in ("test", "pytest", "unittest", "spec")):
        return "test"
    if any(k in lower for k in ("docker", "container", "image")):
        return "docker"
    if any(k in lower for k in ("data", "pandas", "csv", "analysis", "dataset")):
        return "data"
    if any(k in lower for k in ("todo", "task", "list", "checklist")):
        return "todo"
    if any(k in lower for k in ("config", "settings", "configuration")):
        return "config"
    if any(k in lower for k in ("readme", "documentation", "doc")):
        return "readme"
    return "general"


# ── Python templates ──────────────────────────────────────────────────────────

_PY_FASTAPI = '''\
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List
import uvicorn

app = FastAPI(title="{title}", version="0.1.0")

items: dict[int, dict] = {{}}
_next_id = 1


class Item(BaseModel):
    name: str
    description: str = ""
    done: bool = False


class ItemOut(Item):
    id: int


@app.get("/")
def root():
    return {{"status": "ok", "app": "{title}"}}


@app.get("/items", response_model=List[ItemOut])
def list_items():
    return [ItemOut(id=k, **v) for k, v in items.items()]


@app.post("/items", response_model=ItemOut, status_code=201)
def create_item(item: Item):
    global _next_id
    items[_next_id] = item.model_dump()
    out = ItemOut(id=_next_id, **item.model_dump())
    _next_id += 1
    return out


@app.get("/items/{{item_id}}", response_model=ItemOut)
def get_item(item_id: int):
    if item_id not in items:
        raise HTTPException(status_code=404, detail="Item not found")
    return ItemOut(id=item_id, **items[item_id])


@app.delete("/items/{{item_id}}", status_code=204)
def delete_item(item_id: int):
    if item_id not in items:
        raise HTTPException(status_code=404, detail="Item not found")
    del items[item_id]


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
'''

_PY_CLI = '''\
"""Command-line tool: {title}

Generated by apathy on {date}.
"""
from __future__ import annotations

import argparse
import sys


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="{name}",
        description="{title} — a CLI tool",
    )
    parser.add_argument("input", nargs="?", help="Input value or file path")
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")
    parser.add_argument("-o", "--output", default="-", help="Output file (default: stdout)")
    return parser.parse_args()


def run(args: argparse.Namespace) -> int:
    prog = "{title}"
    if args.verbose:
        print("[" + prog + "] starting", file=sys.stderr)

    value = args.input or "hello from " + prog
    out = "Processed: " + str(value)

    if args.output == "-":
        print(out)
    else:
        with open(args.output, "w") as f:
            f.write(out + "\\n")
        if args.verbose:
            print("Written to " + args.output, file=sys.stderr)
    return 0


def main() -> None:
    sys.exit(run(parse_args()))


if __name__ == "__main__":
    main()
'''

_PY_TEST = '''\
"""Tests for {title}.

Generated by apathy on {date}.
"""
from __future__ import annotations

import pytest


class TestCore:
    def test_basic_truthy(self):
        assert True

    def test_basic_math(self):
        assert 1 + 1 == 2

    @pytest.mark.parametrize("value", [1, "hello", []])
    def test_parameterized(self, value):
        assert value is not None or value == []

    def test_list_operations(self):
        items = []
        items.append("a")
        items.append("b")
        assert len(items) == 2
        assert "a" in items

    def test_dict_operations(self):
        d: dict = {{}}
        d["key"] = "value"
        assert d.get("key") == "value"
        assert d.get("missing") is None


class TestEdgeCases:
    def test_empty_string(self):
        assert "" == ""
        assert not ""

    def test_none_handling(self):
        x = None
        assert x is None
        assert not x

    def test_exception_raised(self):
        with pytest.raises(ZeroDivisionError):
            _ = 1 / 0
'''

_PY_DATA = '''\
"""Data analysis script: {title}

Generated by apathy on {date}.
"""
from __future__ import annotations

import csv
import json
import os
import statistics
from pathlib import Path


def load_csv(path: str) -> list[dict]:
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def summarize(records: list[dict]) -> dict:
    if not records:
        return {{"count": 0}}
    numeric: dict[str, list[float]] = {{}}
    for row in records:
        for k, v in row.items():
            try:
                numeric.setdefault(k, []).append(float(v))
            except (ValueError, TypeError):
                pass
    stats = {{"count": len(records)}}
    for col, values in numeric.items():
        stats[col] = {{
            "min": min(values),
            "max": max(values),
            "mean": round(statistics.mean(values), 4),
            "stdev": round(statistics.stdev(values), 4) if len(values) > 1 else 0,
        }}
    return stats


def main() -> None:
    data_dir = Path(os.environ.get("DATA_DIR", "."))
    csv_files = list(data_dir.glob("*.csv"))

    if not csv_files:
        print("No CSV files found. Creating sample dataset...")
        sample_path = data_dir / "sample.csv"
        with open(sample_path, "w", newline="") as f:
            w = csv.writer(f)
            w.writerow(["id", "value", "category"])
            for i in range(10):
                w.writerow([i + 1, (i + 1) * 3.14, "A" if i % 2 == 0 else "B"])
        csv_files = [sample_path]
        print(f"Created {{sample_path}}")

    for path in csv_files:
        records = load_csv(str(path))
        summary = summarize(records)
        print(f"\\n=== {{path.name}} ===")
        print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
'''

_PY_GENERAL = '''\
"""Module: {title}

Generated by apathy on {date}.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class {class_name}:
    name: str
    data: dict[str, Any] = field(default_factory=dict)
    tags: list[str] = field(default_factory=list)

    def process(self) -> dict[str, Any]:
        return {{
            "name": self.name,
            "data_keys": list(self.data.keys()),
            "tag_count": len(self.tags),
        }}

    def add_tag(self, tag: str) -> None:
        if tag not in self.tags:
            self.tags.append(tag)

    def to_dict(self) -> dict[str, Any]:
        return {{
            "name": self.name,
            "data": self.data,
            "tags": self.tags,
        }}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "{class_name}":
        obj = cls(name=d["name"])
        obj.data = d.get("data", {{}})
        obj.tags = d.get("tags", [])
        return obj


def main() -> None:
    obj = {class_name}(name="example", data={{"key": "value"}}, tags=["demo", "apathy"])
    print(obj.process())


if __name__ == "__main__":
    main()
'''

# ── Shell / config / markup templates ─────────────────────────────────────────

_SH_GENERAL = '''\
#!/usr/bin/env bash
# {title}
# Generated by apathy on {date}
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
LOG_FILE="${{SCRIPT_DIR}}/{name}.log"

log() {{
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"
}}

cleanup() {{
    log "Script finished (exit code: $?)"
}}
trap cleanup EXIT

log "Starting {title}..."
log "Working directory: $SCRIPT_DIR"

# ── main logic ────────────────────────────────────────────────────────────────
echo "Hello from {title}!"
echo "Timestamp: $(date)"
echo "User: $(whoami)"

log "Done."
'''

_DOCKER_GENERAL = '''\
FROM python:3.11-slim

WORKDIR /app

# System dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Application code
COPY . .

# Run as non-root
RUN useradd -m appuser && chown -R appuser /app
USER appuser

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \\
    CMD curl -f http://localhost:8000/ || exit 1

CMD ["python", "main.py"]
'''

_REQUIREMENTS_FASTAPI = '''\
fastapi>=0.111.0
uvicorn[standard]>=0.30.0
pydantic>=2.7.0
httpx>=0.27.0
'''

_REQUIREMENTS_GENERAL = '''\
# Core dependencies
pydantic>=2.7.0
httpx>=0.27.0
pyyaml>=6.0.1
rich>=13.7.0

# Dev dependencies (install with: pip install -r requirements-dev.txt)
# pytest>=8.2.0
# pytest-asyncio>=0.23.0
# ruff>=0.4.0
'''

_JSON_CONFIG = '''\
{{
  "app": "{title}",
  "version": "0.1.0",
  "debug": false,
  "server": {{
    "host": "0.0.0.0",
    "port": 8000,
    "workers": 1
  }},
  "database": {{
    "url": "sqlite:///./app.db",
    "pool_size": 5
  }},
  "logging": {{
    "level": "INFO",
    "format": "%(asctime)s %(levelname)s %(name)s %(message)s"
  }},
  "features": {{
    "enable_docs": true,
    "enable_metrics": false
  }}
}}
'''

_YAML_CONFIG = '''\
# {title} configuration
# Generated by apathy on {date}

app:
  name: "{title}"
  version: "0.1.0"
  debug: false

server:
  host: "0.0.0.0"
  port: 8000
  reload: false

database:
  url: "sqlite:///./app.db"
  echo: false

logging:
  level: INFO
  handlers:
    - type: console
      format: "%(asctime)s %(levelname)s %(message)s"
    - type: file
      path: "./app.log"

features:
  docs: true
  metrics: false
  auth: false
'''

_HTML_GENERAL = '''\
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            background: #0d0d0d;
            color: #e0e0e0;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 2rem;
        }}
        header {{
            border-bottom: 1px solid #333;
            width: 100%;
            max-width: 900px;
            padding-bottom: 1rem;
            margin-bottom: 2rem;
        }}
        h1 {{ color: #9d9dff; font-size: 2rem; }}
        .subtitle {{ color: #666; font-size: 0.9rem; margin-top: 0.25rem; }}
        main {{ width: 100%; max-width: 900px; }}
        .card {{
            background: #1a1a1a;
            border: 1px solid #2a2a2a;
            border-radius: 8px;
            padding: 1.5rem;
            margin-bottom: 1rem;
        }}
        .card h2 {{ color: #ccc; font-size: 1.1rem; margin-bottom: 0.75rem; }}
        input, button {{
            padding: 0.5rem 1rem;
            border-radius: 4px;
            border: 1px solid #333;
            background: #111;
            color: #e0e0e0;
            font-size: 1rem;
        }}
        button {{
            background: #3333aa;
            border-color: #5555cc;
            cursor: pointer;
            transition: background 0.2s;
        }}
        button:hover {{ background: #4444cc; }}
        #output {{
            margin-top: 1rem;
            padding: 1rem;
            background: #111;
            border-radius: 4px;
            font-family: monospace;
            font-size: 0.85rem;
            color: #7fff7f;
            min-height: 60px;
            white-space: pre-wrap;
        }}
        footer {{
            margin-top: 3rem;
            color: #444;
            font-size: 0.75rem;
        }}
    </style>
</head>
<body>
    <header>
        <h1>{title}</h1>
        <div class="subtitle">Gerado por apathy · {date}</div>
    </header>
    <main>
        <div class="card">
            <h2>Ferramenta</h2>
            <input type="text" id="inputField" placeholder="Digite algo..."
                   style="width:70%; margin-right:0.5rem;">
            <button onclick="process()">Executar</button>
            <div id="output">Aguardando entrada...</div>
        </div>
        <div class="card">
            <h2>Status</h2>
            <div id="status">Pronto.</div>
        </div>
    </main>
    <footer>Powered by apathy agent framework</footer>
    <script>
        function process() {{
            const val = document.getElementById("inputField").value.trim();
            const out = document.getElementById("output");
            const status = document.getElementById("status");
            if (!val) {{ out.textContent = "Entrada vazia."; return; }}
            out.textContent = `Processado: ${{val}}\\nTimestamp: ${{new Date().toISOString()}}`;
            status.textContent = "OK · " + new Date().toLocaleTimeString();
        }}
        document.getElementById("inputField").addEventListener("keydown", e => {{
            if (e.key === "Enter") process();
        }});
    </script>
</body>
</html>
'''

_MD_README = '''\
# {title}

> Generated by **apathy** on {date}

## Overview

{title} is a project scaffolded by the apathy agent framework.
Replace this section with your actual project description.

## Features

- [x] Project structure generated
- [x] Core modules in place
- [ ] Tests passing
- [ ] CI/CD configured
- [ ] Documentation complete

## Getting Started

```bash
# Install dependencies
pip install -r requirements.txt

# Run the application
python main.py

# Run tests
pytest tests/ -v
```

## Project Structure

```
.
├── main.py          # Entry point
├── requirements.txt # Dependencies
├── config.json      # Configuration
├── tests/           # Test suite
└── README.md        # This file
```

## Configuration

Copy `config.json` and adjust values for your environment.
The `debug` flag enables verbose logging.

## Development

```bash
# Linting
ruff check .

# Format
ruff format .

# Type check
mypy .
```

## License

MIT © {year}
'''

_MD_GENERAL = '''\
# {title}

> Generated by **apathy** on {date}

## Summary

This document covers {title}.

## Details

Add your content here.

## Notes

- Item one
- Item two
- Item three

---
*Generated by apathy agent framework*
'''

_TODO_TXT = '''\
# TODO — {title}
# Generated by apathy on {date}

## High Priority
- [ ] Define core requirements
- [ ] Set up project structure
- [ ] Implement main module
- [ ] Write unit tests

## Medium Priority
- [ ] Add error handling
- [ ] Write documentation
- [ ] Set up CI/CD
- [ ] Code review

## Low Priority
- [ ] Performance optimization
- [ ] Add metrics/logging
- [ ] Prepare release

## Done
- [x] Project scaffolded by apathy
'''

_ENV_EXAMPLE = '''\
# Environment variables — {title}
# Copy this file to .env and fill in your values
# NEVER commit .env to version control

# Application
APP_ENV=development
APP_SECRET=change-me-in-production
DEBUG=false

# Database
DATABASE_URL=sqlite:///./app.db

# API keys (optional)
# ANTHROPIC_API_KEY=
# OPENAI_API_KEY=
# OLLAMA_BASE_URL=http://localhost:11434

# Server
HOST=0.0.0.0
PORT=8000
'''

_GITIGNORE = '''\
# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
dist/
*.egg-info/
.eggs/

# Virtual environments
.venv/
venv/
env/

# Secrets
.env
*.key
*.pem
secrets/

# Editors
.vscode/
.idea/
*.swp
*.swo

# Testing
.pytest_cache/
.coverage
htmlcov/

# Misc
.DS_Store
*.log
tmp/
'''

_MAKEFILE = '''\
.PHONY: install test lint format run clean

install:
\tuv sync

test:
\tuv run pytest tests/ -v

lint:
\tuv run ruff check .

format:
\tuv run ruff format .

run:
\tuv run python main.py

clean:
\tfind . -type d -name __pycache__ -exec rm -rf {{}} + 2>/dev/null || true
\trm -rf .pytest_cache htmlcov .coverage dist build *.egg-info
'''


_CSS_DARK_THEME = '''\
/* {title} — dark base styles
   Generated by apathy on {date}
*/
*, *::before, *::after {{
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}}

:root {{
  --bg: #0d0d0d;
  --surface: #1a1a1a;
  --border: #2a2a2a;
  --text: #e0e0e0;
  --muted: #666;
  --accent: #9d9dff;
  --accent-hover: #bbbbff;
  --success: #7fff7f;
  --error: #ff7f7f;
  --font-sans: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  --font-mono: "JetBrains Mono", "Fira Code", "Cascadia Code", monospace;
  --radius: 6px;
  --shadow: 0 2px 8px rgba(0, 0, 0, 0.4);
}}

html {{
  font-size: 16px;
  scroll-behavior: smooth;
}}

body {{
  font-family: var(--font-sans);
  background: var(--bg);
  color: var(--text);
  min-height: 100vh;
  line-height: 1.6;
}}

a {{
  color: var(--accent);
  text-decoration: none;
}}
a:hover {{
  color: var(--accent-hover);
  text-decoration: underline;
}}

h1, h2, h3, h4, h5, h6 {{
  color: var(--accent);
  line-height: 1.2;
  margin-bottom: 0.5em;
}}

p {{
  margin-bottom: 1em;
}}

code, pre {{
  font-family: var(--font-mono);
  background: var(--surface);
  border-radius: var(--radius);
}}

code {{
  padding: 0.1em 0.3em;
  font-size: 0.9em;
}}

pre {{
  padding: 1rem;
  overflow-x: auto;
  border: 1px solid var(--border);
}}

.container {{
  width: 100%;
  max-width: 960px;
  margin: 0 auto;
  padding: 0 1rem;
}}

.card {{
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 1.5rem;
  box-shadow: var(--shadow);
}}

button, .btn {{
  display: inline-flex;
  align-items: center;
  gap: 0.4em;
  padding: 0.5rem 1.25rem;
  background: #3333aa;
  color: var(--text);
  border: 1px solid #5555cc;
  border-radius: var(--radius);
  font-size: 0.95rem;
  cursor: pointer;
  transition: background 0.2s, border-color 0.2s;
}}

button:hover, .btn:hover {{
  background: #4444cc;
  border-color: var(--accent);
}}

input, textarea, select {{
  background: #111;
  color: var(--text);
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 0.5rem 0.75rem;
  font-size: 1rem;
  width: 100%;
}}

input:focus, textarea:focus, select:focus {{
  outline: none;
  border-color: var(--accent);
}}

/* Utility classes */
.text-muted {{ color: var(--muted); }}
.text-accent {{ color: var(--accent); }}
.text-success {{ color: var(--success); }}
.text-error {{ color: var(--error); }}
.mt-1 {{ margin-top: 0.5rem; }}
.mt-2 {{ margin-top: 1rem; }}
.mt-3 {{ margin-top: 1.5rem; }}
.mb-1 {{ margin-bottom: 0.5rem; }}
.mb-2 {{ margin-bottom: 1rem; }}
.flex {{ display: flex; }}
.flex-col {{ flex-direction: column; }}
.items-center {{ align-items: center; }}
.gap-1 {{ gap: 0.5rem; }}
.gap-2 {{ gap: 1rem; }}
'''

_JS_MODULE = '''\
/**
 * {title}
 * Generated by apathy on {date}
 */

// ── State ────────────────────────────────────────────────────────────────────

const state = {{
  data: [],
  loading: false,
  error: null,
}};

// ── Utilities ────────────────────────────────────────────────────────────────

/**
 * Lightweight fetch wrapper with JSON handling and error propagation.
 * @param {{string}} url
 * @param {{RequestInit}} [options]
 * @returns {{Promise<any>}}
 */
async function fetchJSON(url, options = {{}}) {{
  const response = await fetch(url, {{
    headers: {{ "Content-Type": "application/json", ...options.headers }},
    ...options,
  }});
  if (!response.ok) {{
    const text = await response.text().catch(() => response.statusText);
    throw new Error(`HTTP ${{response.status}}: ${{text}}`);
  }}
  return response.json();
}}

/**
 * Format bytes into a human-readable string.
 * @param {{number}} bytes
 * @returns {{string}}
 */
function formatBytes(bytes) {{
  if (bytes < 1024) return `${{bytes}} B`;
  if (bytes < 1024 ** 2) return `${{(bytes / 1024).toFixed(1)}} KB`;
  return `${{(bytes / 1024 ** 2).toFixed(2)}} MB`;
}}

/**
 * Debounce a function call.
 * @param {{Function}} fn
 * @param {{number}} ms
 * @returns {{Function}}
 */
function debounce(fn, ms = 300) {{
  let timer;
  return (...args) => {{
    clearTimeout(timer);
    timer = setTimeout(() => fn(...args), ms);
  }};
}}

// ── DOM Helpers ───────────────────────────────────────────────────────────────

/**
 * Select a single element or throw.
 * @param {{string}} selector
 * @param {{Element}} [root]
 * @returns {{Element}}
 */
function qs(selector, root = document) {{
  const el = root.querySelector(selector);
  if (!el) throw new Error(`Element not found: ${{selector}}`);
  return el;
}}

/**
 * Create an element with optional attrs and children.
 * @param {{string}} tag
 * @param {{Record<string,string>}} [attrs]
 * @param {{(string|Element)[]}} [children]
 * @returns {{HTMLElement}}
 */
function el(tag, attrs = {{}}, children = []) {{
  const node = document.createElement(tag);
  for (const [k, v] of Object.entries(attrs)) {{
    if (k === "className") node.className = v;
    else node.setAttribute(k, v);
  }}
  for (const child of children) {{
    node.append(typeof child === "string" ? document.createTextNode(child) : child);
  }}
  return node;
}}

// ── API Layer ─────────────────────────────────────────────────────────────────

const API_BASE = "";  // Replace with your API base URL

const api = {{
  async getItems() {{
    return fetchJSON(`${{API_BASE}}/items`);
  }},
  async createItem(data) {{
    return fetchJSON(`${{API_BASE}}/items`, {{
      method: "POST",
      body: JSON.stringify(data),
    }});
  }},
  async deleteItem(id) {{
    return fetchJSON(`${{API_BASE}}/items/${{id}}`, {{ method: "DELETE" }});
  }},
}};

// ── Render ────────────────────────────────────────────────────────────────────

function renderItem(item) {{
  return el("div", {{ className: "card mb-1" }}, [
    el("strong", {{}}, [item.name || String(item.id)]),
    " — ",
    el("span", {{ className: "text-muted" }}, [JSON.stringify(item)]),
  ]);
}}

function renderList(items, container) {{
  container.innerHTML = "";
  if (!items.length) {{
    container.append(el("p", {{ className: "text-muted" }}, ["No items yet."]));
    return;
  }}
  for (const item of items) {{
    container.append(renderItem(item));
  }}
}}

// ── Event Handlers ────────────────────────────────────────────────────────────

function init() {{
  const output = document.getElementById("output");
  const inputField = document.getElementById("inputField");
  const statusEl = document.getElementById("status");

  if (!output || !inputField) return;

  function setStatus(msg, isError = false) {{
    if (!statusEl) return;
    statusEl.textContent = msg;
    statusEl.className = isError ? "text-error" : "text-success";
  }}

  async function handleSubmit() {{
    const value = inputField.value.trim();
    if (!value) {{
      output.textContent = "Please enter a value.";
      return;
    }}
    output.textContent = `Processed: ${{value}}\\nTimestamp: ${{new Date().toISOString()}}`;
    setStatus("OK · " + new Date().toLocaleTimeString());
    inputField.value = "";
  }}

  const btn = document.getElementById("submitBtn");
  if (btn) btn.addEventListener("click", handleSubmit);

  inputField.addEventListener("keydown", (e) => {{
    if (e.key === "Enter") handleSubmit();
  }});

  // Expose for debugging
  window._state = state;
  window._api = api;
}}

// ── Bootstrap ─────────────────────────────────────────────────────────────────

if (document.readyState === "loading") {{
  document.addEventListener("DOMContentLoaded", init);
}} else {{
  init();
}}
'''


# ── Public API ────────────────────────────────────────────────────────────────

def generate_content(path: str, task_text: str = "") -> str:
    """Return appropriate template content for *path* given *task_text* context."""
    ext = os.path.splitext(path)[1].lower()
    name = os.path.splitext(os.path.basename(path))[0]
    title = _title(path)
    class_name = re.sub(r"[^a-zA-Z0-9]", "", title.replace(" ", ""))
    if not class_name or not class_name[0].isalpha():
        class_name = "App" + class_name
    date = datetime.now().strftime("%Y-%m-%d")
    year = datetime.now().strftime("%Y")
    topic = _detect_topic(task_text + " " + path)

    ctx = {"title": title, "name": name, "class_name": class_name, "date": date, "year": year}

    if ext == ".py":
        if topic == "fastapi":
            return _PY_FASTAPI.format(**ctx)
        if topic == "cli":
            return _PY_CLI.format(**ctx)
        if topic == "test" or name.startswith("test_"):
            return _PY_TEST.format(**ctx)
        if topic == "data":
            return _PY_DATA.format(**ctx)
        return _PY_GENERAL.format(**ctx)

    if ext in (".sh", ".bash"):
        return _SH_GENERAL.format(**ctx)

    if ext in (".dockerfile",) or os.path.basename(path) == "Dockerfile":
        return _DOCKER_GENERAL.format(**ctx)

    if name == "requirements" and ext == ".txt":
        if topic == "fastapi":
            return _REQUIREMENTS_FASTAPI.format(**ctx)
        return _REQUIREMENTS_GENERAL.format(**ctx)

    if ext == ".json":
        return _JSON_CONFIG.format(**ctx)

    if ext in (".yaml", ".yml"):
        return _YAML_CONFIG.format(**ctx)

    if ext in (".html", ".htm"):
        return _HTML_GENERAL.format(**ctx)

    if ext == ".md":
        if name.lower() == "readme":
            return _MD_README.format(**ctx)
        return _MD_GENERAL.format(**ctx)

    if ext == ".txt":
        if topic == "todo" or "todo" in name.lower():
            return _TODO_TXT.format(**ctx)
        # plain text — use task as content if it looks like content
        return f"# {title}\nGenerated by apathy on {date}\n\n{task_text or 'Content goes here.'}\n"

    if name == ".env.example" or name == ".env":
        return _ENV_EXAMPLE.format(**ctx)

    if name == ".gitignore":
        return _GITIGNORE.format(**ctx)

    if name in ("Makefile", "makefile"):
        return _MAKEFILE.format(**ctx)

    if ext == ".css":
        return _CSS_DARK_THEME.format(**ctx)

    if ext == ".js":
        return _JS_MODULE.format(**ctx)

    # Fallback: generic marker so it's clear it came from apathy
    return f"# {title}\n# Generated by apathy on {date}\n# Task: {task_text or 'n/a'}\n"


def make_project_plan(
    project_type: str,
    workspace: str,
    name: str = "myapp",
) -> list[dict[str, str]]:
    """Return an ordered list of {path, task} dicts for a complete project.

    Each dict has:
      path  — absolute file path to write
      task  — natural-language description used to select the right template
    """
    import os as _os

    pt = project_type.lower().strip()

    def p(*parts: str) -> str:
        return _os.path.join(workspace, *parts)

    if pt in ("fastapi", "api", "rest"):
        return [
            {"path": p("main.py"), "task": f"fastapi api application named {name}"},
            {"path": p("models.py"), "task": f"fastapi pydantic models for {name}"},
            {"path": p("requirements.txt"), "task": "fastapi project requirements"},
            {"path": p("config.json"), "task": f"configuration for {name}"},
            {"path": p("Dockerfile"), "task": "docker image for python fastapi app"},
            {"path": p(".env.example"), "task": "environment variables example"},
            {"path": p(".gitignore"), "task": "python gitignore"},
            {"path": p("Makefile"), "task": "makefile with install test lint run targets"},
            {"path": p("tests", "test_app.py"), "task": f"pytest tests for fastapi {name}"},
            {"path": p("README.md"), "task": f"readme for {name} fastapi project"},
        ]

    if pt in ("cli", "tool"):
        return [
            {"path": p("main.py"), "task": f"cli command line tool named {name}"},
            {"path": p("requirements.txt"), "task": "cli tool requirements"},
            {"path": p("config.yaml"), "task": f"yaml configuration for {name}"},
            {"path": p("Makefile"), "task": "makefile with install test lint run targets"},
            {"path": p("tests", "test_cli.py"), "task": f"pytest tests for cli {name}"},
            {"path": p("README.md"), "task": f"readme for {name} cli tool"},
            {"path": p(".gitignore"), "task": "python gitignore"},
        ]

    if pt in ("webapp", "web", "html"):
        return [
            {"path": p("index.html"), "task": f"html webapp named {name}"},
            {"path": p("style.css"), "task": f"dark theme css styles for {name}"},
            {"path": p("app.js"), "task": f"vanilla javascript module for {name} webapp"},
            {"path": p("config.json"), "task": f"configuration for {name}"},
            {"path": p("README.md"), "task": f"readme for {name} webapp"},
            {"path": p(".gitignore"), "task": "gitignore for web project"},
        ]

    if pt in ("data", "analysis"):
        return [
            {"path": p("analysis.py"), "task": f"data analysis script named {name}"},
            {"path": p("requirements.txt"), "task": "data analysis requirements"},
            {"path": p("config.yaml"), "task": f"yaml configuration for {name}"},
            {"path": p("Makefile"), "task": "makefile with install test lint run targets"},
            {"path": p("tests", "test_analysis.py"), "task": f"pytest tests for data {name}"},
            {"path": p("README.md"), "task": f"readme for {name} data project"},
        ]

    # default — fastapi
    return make_project_plan("fastapi", workspace, name)
